[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version="Cancun"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
arbitrum = "${ARB_RPC_URL}"
sepolia = "https://rpc.buildbear.io/sanam"
ethereum = "https://virtual.mainnet.rpc.tenderly.co/0391d9fa-0553-482f-9dac-6eb34f75001c" 
